[tool.coverage.run]
omit = ["*/__init__.py"]
timid = true

[tool.pytest.ini_options]
python_files = ["test_*.py"]
addopts = "-m unit -v --cov-config=.coveragerc --cov=mdfparser --cov-report=xml"
filterwarnings = [
    'ignore:\nPyarrow:DeprecationWarning', # Warning to collect feedback about pyarrow(https://github.com/pandas-dev/pandas/issues/54466)
]
markers = [
    "unit",
    "integration"
]

[tool.autopep8]
max_line_length = 120
recursive = true
aggressive = 3
ignore = ["E231"] # Avoids this bug https://github.com/hhatto/autopep8/issues/712

[tool.pylint]
recursive = true
check-quote-consistency = true
ignored-modules = "setuptools"
# We need to include base path in pylint config
init-hook = "import sys; sys.path.append('../base');"

[tool.pylint.format]
# Maximum number of characters on a single line.
max-line-length = 120

ignore-patterns="(.)*_test\\.py,test_(.)*\\.py,conftest.py"

[tool.mypy]
files = [
    "mdfparser/**/*.py"
]
exclude = [
    "^test.*\\.py$",
    "conftest.py",
]
# mypy per-module options:
[[tool.mypy.overrides]]
module = "base.*"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "setuptools"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "pytimeparse"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "mergedeep"
ignore_missing_imports = true

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B101"]
