version: '3.5'
services:
    app:
      build:
        context: .
        args:
          NPM_EMAIL: -USE-YOUR-OWN-ARTIFACTORY-KEY-
          NPM_AUTH: -USE-YOUR-OWN-ARTIFACTORY-KEY-
      ports:
        - '4200:80'
      environment:
        - API_URL=https://ai-test.bosch-ridecare.com/api/
        - AZURE_CLIENT_ID=b74f0fea-4e4a-4785-886a-96c1922dfb7b
        - AZURE_AUTHORITY=https://login.microsoftonline.com/0ae51e19-07c8-4e4b-bb6d-648ee58410f4
        - OWN_URL=http://localhost:4200
