excludes:
  paths:
    - pattern: ".github/**"
      reason: "BUILD_TOOL_OF"
      comment: "Github actions and workflows are not included in a build"
    - pattern: ".vscode/**"
      reason: "BUILD_TOOL_OF"
      comment: "Configuration for developer environment only"
    - pattern: "**/tests/**"
      reason: "TEST_OF"
      comment: "Tests of the micro services"
    - pattern: "**/requirements_dev.txt"
      reason: "BUILD_TOOL_OF"
      comment: "Packages for development only."
  scopes:
    - pattern: "devDependencies"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."
