[tool.coverage.run]
omit = ["*/__init__.py"]
timid = true

[tool.pytest.ini_options]
python_files = ["test_*.py"]
addopts = "-m unit -v --cov-config=.coveragerc --cov=labeling_bridge --cov-report=xml"
markers = [
    "unit",
    "integration"
]
filterwarnings = [
    'ignore:\nPyarrow:DeprecationWarning', # Warning to collect feedback about pyarrow(https://github.com/pandas-dev/pandas/issues/54466)
    'ignore:jsonschema.RefResolver', # To be fixe din upcomming versions of flask-restx(https://github.com/python-restx/flask-restx/issues/553),
    'ignore:No uuid:DeprecationWarning', # Requires update in pymongo dependecy which is pinned in voxel51 at 0.25.3
    'ignore:No :DeprecationWarning', # Issue on mongoengine
    'ignore:Call to deprecated class Frame', # Kognic issue
    'ignore:Call to deprecated class Cameras' # Kognic issue
]


[tool.autopep8]
max_line_length = 120
recursive = true
aggressive = 3
ignore = ["E231"] # Avoids this bug https://github.com/hhatto/autopep8/issues/712

[tool.pylint]
recursive = true
check-quote-consistency = true
ignored-modules = "setuptools"
# We need to include base path in pylint config
init-hook = "import sys; sys.path.append('../base');"

[tool.pylint.format]
# Maximum number of characters on a single line.
max-line-length = 120


[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"

[tool.mypy]
files = [
    "labeling_bridge/**/*.py",
    "tests/**/*.py"
]
# mypy per-module options:
[[tool.mypy.overrides]]
module = "setuptools"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "base.*"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "flask_restx"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "flask_cors"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "fiftyone.*"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "kognic.*"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "mongoengine.*"
ignore_missing_imports = true

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B101"]
