name: SAST Scan
description: Perform Bandit Security Scan
inputs:
  baseDir:
    description: Path to base directory
    required: true
  python-version:
    description: Python version
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install pip dependencies ${{ inputs.baseDir }}
      shell: bash
      run: |
        pushd ${{ inputs.baseDir }}
        trap popd EXIT
        python -m pip install bandit bandit[toml]

    - name: Run bandit scan
      shell: bash
      run: |
        pushd ${{ inputs.baseDir }}
        trap popd EXIT
        bandit -v --exit-zero -r ${PWD} -c pyproject.toml -f json -o bandit_report.json

        echo "::group::troubleshoot-report"
        cat bandit_report.json
        echo "::endgroup::"

    - name: Fix analysis paths
      # Necessary step to correct source paths, since sonar scanner works from a Docker container and has a different path structure from github
      shell: bash
      run: |
        sed -i 's/\/home\/runner\/work\/container_scripts\/container_scripts\//\/github\/workspace\//g' ${{ inputs.baseDir }}/bandit_report.json

    - name: Persist ${{ inputs.baseDir }} security report
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.baseDir }}-security-report
        path: ${{ inputs.baseDir }}/bandit_report.json
