name: Test Javascript
description: Performs testing in a Javascript Project
inputs:
  baseDir:
    description: Path to base directory
    required: true
  node-version:
    description: Node version
    required: true
  npm-registry:
    description: NPM registry
    required: true
  npm-auth:
    description: NPM auth
    required: true
  npm-email:
    description: NPM email
    required: true

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"
        cache-dependency-path: '**/package-lock.json'
        always-auth: true
    - name: Setup auth in npm
      env:
        NPM_REGISTRY: ${{ inputs.npm-registry }}
        NPM_AUTH: ${{ inputs.npm-auth }}
        NPM_EMAIL: ${{ inputs.npm-email }}
      shell: bash
      run: |
        PREFIX="https:"
        # Scope fragment needs to be without http(s) prefix
        REPO_FRAGMENT=${NPM_REGISTRY#"$PREFIX"}
        npm config set registry
        # Scope auth to given registry
        npm config set $REPO_FRAGMENT:_auth $NPM_AUTH
        npm config set email $NPM_EMAIL
    - name: Install npm dependencies ${{ inputs.baseDir }}
      shell: bash
      run: |
        trap popd EXIT
        pushd ${{ inputs.baseDir }}
        npm ci
    - name: Run tests for ${{ inputs.baseDir }}
      shell: bash
      continue-on-error: true
      run: |
        trap popd EXIT
        pushd ${{ inputs.baseDir }}
        npm run test-headless

    - name: Persist ${{ inputs.baseDir }} coverage report
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.baseDir }}-coverage-report-unit
        path: ${{ inputs.baseDir }}/coverage/ridecare-devcloud/lcov.info
