# example config
# this config is not used on the cluster. If you are looking for the current version check:
# QA: https://github.com/bosch-rc-dev/kubernetes_config/blob/master/apps/qa/config_maps/tenant_mapping_config.yaml
dataset_mapping:
  create_dataset_for:
    - ridecare_companion_gridwise
  default_dataset: Debug_Lync
  tag: RC
