[tool.coverage.run]
omit = ["*/__init__.py"]
timid = true

[tool.pytest.ini_options]
python_files = ["test_*.py", "helper_functions.py"]
asyncio_mode = "auto"
addopts = "-m unit -v --cov-config=.coveragerc --cov=artifact_api --cov-report=xml"
filterwarnings = [
    "ignore::DeprecationWarning:botocore.*", # Botocore uses datetime.datetime.utcnow() which is deprecated in python 3.12
    "ignore::DeprecationWarning:fiftyone.*", # fiftyone uses datetime.datetime.utcnow() which is deprecated in python 3.12
]
markers = [
    "unit",
    "integration"
]

[tool.autopep8]
max_line_length = 120
recursive = true
aggressive = 3
ignore = ["E231"] # Avoids this bug https://github.com/hhatto/autopep8/issues/712

[tool.pylint]
recursive = true
check-quote-consistency = true
# We need to include base path in pylint config
init-hook = "import sys; sys.path.append('../base');"
ignored-modules = "setuptools"

[tool.pylint.format]
# Maximum number of characters on a single line.
max-line-length = 120

[tool.mypy]
files = [
    "artifact_api/**/*.py",
    "tests/**/test_*.py"
]
exclude = [
    "^test.*\\.py$",
    "conftest.py",
]
# mypy per-module options:
[[tool.mypy.overrides]]
module = "base.*"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "setuptools"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "pymongo.*"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "flask_restx"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "mongoengine.*"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "fiftyone.*"
ignore_missing_imports = true

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B101"]
