version: '3'
services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.9"
        NODE_VERSION: "none"
        TOKEN: "${TOKEN}"
    volumes:
      - ../:/workspace
      - ~/.aws:/home/vscode/.aws
    command: sh -c "while sleep 1000; do :; done"

  plantuml:
    image: plantuml/plantuml-server:jetty
