"""Contants module."""
CONTAINER_NAME = "Healthcheck"
ELASTIC_ALERT_MATCHER = "HEALTHCHECK_ALERT"
ELASTIC_SUCCESS_MATCHER = "HEALTHCHECK_SUCCESS"
TWELVE_HOURS_IN_SECONDS = 60 * 60 * 12
LOOP_DELAY_SECONDS = 5
