apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: container-scripts
manifests:
  kustomize:
    paths:
      # this includes all locally available services
      - ../../kubernetes_config/apps/pg/selector
      - ../../kubernetes_config/apps/pg/mdfparser
      - ../../kubernetes_config/apps/pg/sdm
      - ../../kubernetes_config/apps/pg/voxel-stack
      - ../../kubernetes_config/apps/pg/data_importer
    buildArgs:
      - "--load-restrictor=LoadRestrictionsNone"
build:
    local:
      push: false
      concurrency: 3
    artifacts:
      #SDM
    - image: 081962623310.dkr.ecr.eu-central-1.amazonaws.com/sdm
      context: ..
      docker:
        dockerfile: SDM/Dockerfile
      runtimeType: python
    - image: 081962623310.dkr.ecr.eu-central-1.amazonaws.com/selector
      context: ..
      docker:
        dockerfile: Selector/Dockerfile
      runtimeType: python
      #MDFParser
    - image: 081962623310.dkr.ecr.eu-central-1.amazonaws.com/mdfparser
      context: ..
      docker:
        dockerfile: MDFParser/Dockerfile
      runtimeType: python
    - image: 081962623310.dkr.ecr.eu-central-1.amazonaws.com/data_importer
      context: ..
      docker:
        dockerfile: data_importer/Dockerfile
        secrets:
          - id: voxel51token
            env: TOKEN
      runtimeType: python
deploy:
  # Set this value according to your needs. Very dangerous since you can destroy the full deployment of an application if you point to the wrong context (aka wrong)
  kubeContext: kind-kind

profiles:
- name: local
  activation:
    - kubeContext: kind-kind

portForward:
  - resourceType: Service
    resourceName: voxel
    namespace: data-ingestion
    port: 5151
    localPort: 5151
  - resourceType: Service
    resourceName: mongodb
    namespace: data-ingestion
    port: 27017
    localPort: 27017
