[tool.coverage.run]
omit = ["*/__init__.py"]
timid = true

[tool.pytest.ini_options]
python_files = ["test_*.py"]
addopts = "-m unit -v --cov-config=.coveragerc --cov=artifact_downloader --cov-report=xml"
markers = [
    "unit",
    "integration"
]

[tool.autopep8]
max_line_length = 120
recursive = true
aggressive = 3
ignore = ["E231"] # Avoids this bug https://github.com/hhatto/autopep8/issues/712

[tool.pylint]
recursive = true
check-quote-consistency = true
load-plugins = [
    "pylint_pydantic"
]
# We need to include base path in pylint config
init-hook = "import sys; sys.path.append('../base');"
ignore-paths = [
  "tests/.*$",
]
ignored-modules = "setuptools"

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"

[tool.pylint.format]
# Maximum number of characters on a single line.
max-line-length = 120

[tool.mypy]
files = [
    "artifact_downloader/**/*.py",
    "tests/**/*.py"
]
plugins = [
    "pydantic.mypy"
]
exclude = [
    "^test.*\\.py$",
    "conftest.py",
]
# mypy per-module options:
[[tool.mypy.overrides]]
module = "base.*"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "setuptools"
ignore_missing_imports = true

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B101"]
