[tool.coverage.run]
omit = ["*/__init__.py"]
timid = true

[tool.pytest.ini_options]
python_files = ["test_*.py"]
addopts = "-m unit -v --cov-config=.coveragerc --cov=selector --cov-report=xml"
markers = [
    "unit",
    "integration"
]
filterwarnings = [
    'ignore:No uuid:DeprecationWarning', # Requires update in mongoengine dependecy which is pinned in voxel51 at 0.25.3
    'ignore:pkg_resources:DeprecationWarning' # Outdated mongomock dependency
]

[tool.autopep8]
max_line_length = 120
recursive = true
aggressive = 3
ignore = ["E231"] # Avoids this bug https://github.com/hhatto/autopep8/issues/712

[tool.pylint]
recursive = true
load-plugins = [
    "pylint_pydantic",
]
ignored-modules = "setuptools"
# We need to include base path in pylint config
init-hook = "import sys; sys.path.append('../base');"
ignore-patterns="(.)*_test\\.py,test_(.)*\\.py,conftest.py"

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"

[tool.pylint.format]
# Maximum number of characters on a single line.
max-line-length = 120

[tool.mypy]
plugins = [
  "pydantic.mypy"
]
files = [
    "selector/**/*.py"
]
# mypy per-module options:
[[tool.mypy.overrides]]
module = "base.*"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "setuptools"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "mongoengine.*"
ignore_missing_imports = true

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B101"]
